repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --force-exclude
        language: system
        pass_filenames: true
        types: [python]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --force-exclude
        language: system
        pass_filenames: true
        types: [python]

      - id: bandit
        name: bandit
        entry: uv run bandit -c pyproject.toml
        language: system
        pass_filenames: true
        types: [python]
        exclude: ^(migrations/|.venv/|venv/|tests/)

      - id: ty-check
        name: ty check
        entry: uvx ty check
        language: system
        pass_filenames: true
        types: [python]
        exclude: ^(migrations/|.venv/|venv/|tests/)
